### PR TITLE
[FIX] Fix 2 issues on the action helper

### LINKED ISSUE #3: Actions with parameters not working
When using an action with some paramters, it triggers js errors (the arguments are not handled as they should I guess on the overridden `action` helper:
```handlebars
<button {{action 'someAction' myFirstParam mySecondParam}}>click here</button>
```

I guess it's related to another issue I have where the action of a form would not be called:
```handlebars
<form {{action 'someAction' on='submit'}}>
  <!-- ... -->
  <button type="submit">Send</button>
</form>
```

The `someAction` never get called here.

### PR DESCRIPTION
**Pull request by huafu**
- [x] Fix the JS error when the action helper is used with multiple parameters
- [x] Fix the issue when `<form>` with `{{action ... on='submit'}}` will silently **not** call the desired action at all

The purpose of this PR is to fix #3

### CODE REVIEW

**Comment by huafu** [comment]
Please consider this as a WIP, as you can see on this PR comment the second task isn't done yet ;-)

**Comment by huafu** [comment]
@runspired after a long talk with `mmum` and `rwjblue` from the EmberJS team on IRC, the issue here is that `Ember.Handlebars.helpers` is private and should not be accessed. They suggest to trigger a `click` event on `tap` instead of overriding it in there. Also with HTMLBars the helpers are not functions anymore but objects, so we'll have another issue then. I believe fastclick library does that. So in that case, on the layer on top of Ember (jQuery/DOM) we need to catch the `tap` events somehow and transform them into click on mobile devices.

**Comment by runspired** [comment]
It's good to know that the `arguments.length` approach is backwards compatible, I was worried it wasn't and hadn't dug into that enough yet to be sure (it wasn't something that simply glancing at various portions of the source code revealed).

I do not want to trigger `click`.  There's a few reasons for that.

1. `click` has some behavior expectations would no longer be true.
2. In a mobile-first sense, click is no longer semantically correct.
3. in a mobile context more than one gesture type should be capable of triggering an action.

I have an open Feature request with ember related to this issue: https://github.com/emberjs/ember.js/issues/10090

We're in a mobile-first world now and expecting just `click` to be the src event is not good enough.  The example I give in that feature request is of iOS style on/off sliders.  Native sliders trigger on "tap" "press", "pan" and "swipe".  Essentially, it allows you to craft experiences around a wider range of expected behaviors.  People who want to tap, will tap, but people who want to swipe will swipe.

**Comment by huafu** [comment]
I just pushed a little fix where the `if` was wrong to detect which elements needs to cancel default behavior ;-)

**Comment by zjrosen1** [comment]
@huafu Thanks for this!

**Comment by huafu** [comment]
Welcome!

**Comment by runspired** [comment]
@zjrosen1 @huafu just to let you know this change is published on npm along with the other changes in the changelog for 1.3.0 :)  Thanks again!

**Comment by huafu** [comment]
Awesome, thanks!

--
Huafu Gandon
http://huafu.github.io

**Comment by zjrosen1** [comment]
@runspired appreciate it, keep up the good work!

**Pull request merged**
